import { fetchImageAsBase64 } from "./pptxBuilder";

export async function generatePdfBlob(summary, source, allCustomElements = {}, slides = []) {
  if (!window.jspdf) {
    await new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
      script.onload = resolve;
      script.onerror = () => reject(new Error("Failed to load jsPDF"));
      document.head.appendChild(script);
    });
  }
 
  // Normalize keys to integers
  const normalized = {};
  for (const [k, v] of Object.entries(allCustomElements)) {
    normalized[parseInt(k, 10)] = v || [];
  }
 
  // Pre-convert ALL images (URL strings AND existing base64) to base64
  const resolvedElements = {};
  for (const [slideIdx, elements] of Object.entries(normalized)) {
    const idx = parseInt(slideIdx, 10);
    resolvedElements[String(idx)] = await Promise.all(
      (elements || []).map(async (el) => {
        if (el.type === "image" && el.src) {
          // Already base64 — keep as-is
          if (el.src.startsWith("data:")) return el;
          // URL — convert to base64 so jsPDF can embed it
          const base64 = await fetchImageAsBase64(el.src);
          return base64 ? { ...el, src: base64 } : el; // keep URL if conversion fails
        }
        return el;
      })
    );
  }
 
  return new Promise((resolve, reject) =>
    buildPdf(summary, source, resolvedElements, slides, resolve, reject)
  );
}

// ─── REPLACE your entire buildPdf function with this ──────────────────────────
export function buildPdf(summary, source, allCustomElements, slides, resolve, reject) {
  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 14;
 
    const SLIDE_COLORS = {
      title:      { bg:[15,12,41],   accent:[99,102,241],  tag:"TITLE SLIDE"  },
      overview:   { bg:[10,10,26],   accent:[139,92,246],  tag:"OVERVIEW"     },
      content:    { bg:[5,5,16],     accent:[20,184,166],  tag:"CONTENT"      },
      highlight:  { bg:[13,9,34],    accent:[245,158,11],  tag:"KEY HIGHLIGHT"},
      conclusion: { bg:[15,12,41],   accent:[236,72,153],  tag:"CONCLUSION"   },
    };
 
    const totalPages = 1 + slides.length;
 
    const addPageHeader = () => {
      doc.setFillColor(99, 102, 241);
      doc.rect(0, 0, pageW, 8, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold"); doc.setFontSize(9);
      doc.text("NoteAI", margin, 6);
      doc.setFont("helvetica", "normal"); doc.setFontSize(7);
      doc.text(
        new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" }),
        pageW - margin, 6, { align:"right" }
      );
    };
 
    const addFooter = (pageNum, total) => {
      doc.setFillColor(245, 243, 255);
      doc.rect(0, pageH - 7, pageW, 7, "F");
      doc.setFont("helvetica", "normal"); doc.setFontSize(6.5);
      doc.setTextColor(120, 120, 180);
      doc.text("Generated by NoteAI • Powered by Gemini AI", pageW / 2, pageH - 3, { align:"center" });
      doc.text(`Page ${pageNum} / ${total}`, pageW - margin, pageH - 3, { align:"right" });
    };
 
    // ── PAGE 1: Smart Notes ───────────────────────────────────────────────────
    addPageHeader();
    let y = 14;
 
    if (source) {
      doc.setFillColor(239, 246, 255);
      doc.setDrawColor(99, 102, 241);
      doc.roundedRect(margin, y, pageW - margin * 2, 7, 2, 2, "FD");
      doc.setTextColor(67, 56, 202); doc.setFont("helvetica", "bold"); doc.setFontSize(7);
      doc.text("SOURCE", margin + 2, y + 5);
      doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(30, 27, 75);
      const srcTrunc = source.length > 110 ? source.slice(0, 107) + "…" : source;
      doc.text(srcTrunc, margin + 20, y + 5);
      y += 11;
    }
 
    doc.setTextColor(15, 12, 41); doc.setFont("helvetica", "bold"); doc.setFontSize(18);
    doc.text("Smart Notes", margin, y + 5); y += 10;
    doc.setDrawColor(99, 102, 241); doc.setLineWidth(0.8);
    doc.line(margin, y, margin + 24, y); y += 5;
 
    const noteColW = (pageW - margin * 3) / 2;
    let col = 0, colY = [y, y];
 
    const renderLine = (rawLine) => {
      const line = rawLine.trim();
      if (!line) return;
      const cx = col === 0 ? margin : margin * 2 + noteColW;
      let cy = colY[col];
 
      if (cy > pageH - 14) {
        if (col === 0) { col = 1; cy = colY[1]; }
        else {
          addFooter(1, totalPages);
          doc.addPage(); addPageHeader();
          col = 0; colY = [14, 14]; cy = 14;
        }
      }
 
      if (line.startsWith("# ")) {
        const text = line.replace(/^# /, "").replace(/\*\*/g, "");
        doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(15, 12, 41);
        const wr = doc.splitTextToSize(text, noteColW);
        doc.text(wr, cx, cy); cy += wr.length * 5.5 + 2;
        doc.setDrawColor(180, 180, 220); doc.setLineWidth(0.25);
        doc.line(cx, cy, cx + noteColW, cy); cy += 3;
      } else if (line.startsWith("## ")) {
        const text = line.replace(/^## /, "").replace(/\*\*/g, "").toUpperCase();
        doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(79, 70, 229);
        doc.setFillColor(245, 243, 255);
        const wr = doc.splitTextToSize(text, noteColW - 4);
        doc.rect(cx, cy - 3, noteColW, wr.length * 4.5 + 4, "F");
        doc.text(wr, cx + 2, cy); cy += wr.length * 4.5 + 5;
      } else if (/^[\-\*•] /.test(line)) {
        const text = line.replace(/^[\-\*•] /, "").replace(/\*\*(.*?)\*\*/g, "$1");
        doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(30, 27, 75);
        const wr = doc.splitTextToSize(text, noteColW - 8);
        doc.setFillColor(99, 102, 241);
        doc.circle(cx + 1.8, cy - 1, 0.8, "F");
        doc.text(wr, cx + 6, cy); cy += wr.length * 4.5 + 1;
      } else {
        const text = line.replace(/\*\*(.*?)\*\*/g, "$1");
        doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(30, 27, 75);
        const wr = doc.splitTextToSize(text, noteColW);
        doc.text(wr, cx, cy); cy += wr.length * 4.5 + 1.5;
      }
 
      colY[col] = cy;
      if (col === 0 && colY[0] > colY[1] + 30) col = 1;
      else if (col === 1 && colY[1] > colY[0] + 30) col = 0;
      else if (col === 1 && colY[1] > pageH * 0.6 && colY[0] < pageH * 0.7) col = 0;
    };
 
    summary.split("\n").forEach(renderLine);
    addFooter(1, totalPages);
 
    // ── PAGES 2+: One slide card per page ──────────────────────────────────
    slides.forEach((slide, si) => {
      doc.addPage();
      addPageHeader();
 
      const cfg = SLIDE_COLORS[slide.type] || SLIDE_COLORS.content;
 
      // Canvas pixel dimensions used in the editor preview
      // The slide-canvas-wrap renders at its container width with 56.25% padding-top
      // We map pixel positions → mm using the card dimensions below
      const CARD_X = margin;
      const CARD_Y = 10;
      const CARD_W = pageW - margin * 2;
      const CARD_H = pageH - 10 - 9;
 
      // The "canvas" pixel size we assume when the user dragged elements.
      // The preview renders at ~100% of its CSS container; we normalise against
      // a reference size so positions scale correctly to the PDF card.
      const REF_PX_W = 600;  // reference canvas width in pixels
      const REF_PX_H = 338;  // reference canvas height (600 × 9/16)
 
      // Convert a pixel position/size to mm within the card
      const pxToMmX = (px) => CARD_X + (px / REF_PX_W) * CARD_W;
      const pxToMmY = (py) => CARD_Y + (py / REF_PX_H) * CARD_H;
      const pxToMmW = (pw) => (pw / REF_PX_W) * CARD_W;
      const pxToMmH = (ph) => (ph / REF_PX_H) * CARD_H;
 
      // Slide background
      doc.setFillColor(...cfg.bg);
      doc.roundedRect(CARD_X, CARD_Y, CARD_W, CARD_H, 3, 3, "F");
 
      // Accent top bar
      doc.setFillColor(...cfg.accent);
      doc.roundedRect(CARD_X, CARD_Y, CARD_W, 2.5, 1, 1, "F");
 
      // Slide number
      doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(120, 120, 160);
      doc.text(
        `${String(si + 1).padStart(2, "0")} / ${String(slides.length).padStart(2, "0")}`,
        CARD_X + CARD_W - 4, CARD_Y + 7, { align: "right" }
      );
 
      // Type tag pill
      doc.setFillColor(...cfg.accent.map(c => Math.min(255, c + 60)));
      doc.roundedRect(CARD_X + 4, CARD_Y + 4, 26, 5, 2, 2, "F");
      doc.setTextColor(230, 230, 255); doc.setFontSize(5.5); doc.setFont("helvetica", "bold");
      doc.text(cfg.tag, CARD_X + 17, CARD_Y + 7.8, { align: "center" });
 
      // Slide title
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(slide.type === "title" ? 16 : 12);
      const titleLines = doc.splitTextToSize(slide.title || "", CARD_W - 12);
      doc.text(titleLines, CARD_X + 5, CARD_Y + 16);
      let contentY = CARD_Y + 16 + titleLines.length * (slide.type === "title" ? 8 : 6) + 2;
 
      // Accent divider
      doc.setDrawColor(...cfg.accent); doc.setLineWidth(0.5);
      doc.line(CARD_X + 5, contentY, CARD_X + 20, contentY);
      contentY += 4;
 
      const bullets = (slide.content || "")
        .split("\n")
        .map(l => l.replace(/^[•\-\*]\s*/, "").trim())
        .filter(Boolean);
 
      const INNER_X      = CARD_X + 5;
      const INNER_W      = CARD_W - 10;
      const INNER_BOTTOM = CARD_Y + CARD_H - 8;
 
      // Draw bullets (full width — custom elements are overlaid on top)
      doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(200, 200, 230);
      bullets.forEach(b => {
        if (contentY > INNER_BOTTOM - 3) return;
        doc.setFillColor(...cfg.accent);
        doc.circle(INNER_X + 2, contentY - 1, 0.8, "F");
        const bw = doc.splitTextToSize(b, INNER_W - 8);
        doc.text(bw, INNER_X + 6, contentY);
        contentY += bw.length * 4.2 + 1.2;
      });
 
      // ── Draw custom elements (images, shapes, tables) ─────────────────────
      const elements = allCustomElements[String(si)] || [];
 
      elements.forEach(el => {
        if (!el || !el.position) return;
        const { x, y, width, height } = el.position;
 
        // Convert pixel coords → mm
        const ex = pxToMmX(x);
        const ey = pxToMmY(y);
        const ew = pxToMmW(width);
        const eh = pxToMmH(height);
 
        // Guard: skip if outside card bounds
        if (ex < CARD_X || ey < CARD_Y || ex + ew > CARD_X + CARD_W + 2) return;
 
        // ── IMAGE ──────────────────────────────────────────────────────────
// Find the image block in buildPdf and replace the entire if block:
if (el.type === "image" && el.src && el.src.startsWith("data:")) {
  try {
    const fmt = el.src.startsWith("data:image/png") ? "PNG" : "JPEG";
    const AR = width / Math.max(height, 1);
    let dw = ew, dh = ew / AR;
    if (dh > eh) { dh = eh; dw = eh * AR; }
    const dx = ex + (ew - dw) / 2;
    const dy = ey + (eh - dh) / 2;
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(ex, ey, ew, eh, 1.5, 1.5, "F");
    doc.addImage(el.src, fmt, dx, dy, dw, dh);
  } catch (imgErr) {
    doc.setFillColor(30, 30, 60);
    doc.roundedRect(ex, ey, ew, eh, 1.5, 1.5, "F");
    doc.setTextColor(100, 100, 140); doc.setFontSize(7);
    doc.text("Image", ex + ew / 2, ey + eh / 2, { align: "center" });
  }
}
 
        // ── SHAPE ──────────────────────────────────────────────────────────
        if (el.type === "shape") {
          const shapeId = el.shape || "rectangle";
 
          // Accent colour for shape fill (use slide accent, slightly lighter)
          const [r, g, b] = cfg.accent;
          doc.setFillColor(
            Math.min(255, r + 40),
            Math.min(255, g + 40),
            Math.min(255, b + 80)
          );
          doc.setDrawColor(r, g, b);
          doc.setLineWidth(0.4);
 
          if (shapeId === "line") {
            doc.setDrawColor(...cfg.accent);
            doc.setLineWidth(1.2);
            doc.line(ex, ey + eh / 2, ex + ew, ey + eh / 2);
 
          } else if (shapeId === "rectangle" || shapeId === "roundedRect") {
            const rx = shapeId === "roundedRect" ? Math.min(ew, eh) * 0.15 : 0;
            if (rx > 0) {
              doc.roundedRect(ex, ey, ew, eh, rx, rx, "FD");
            } else {
              doc.rect(ex, ey, ew, eh, "FD");
            }
 
          } else if (shapeId === "circle") {
            doc.ellipse(ex + ew / 2, ey + eh / 2, ew / 2, eh / 2, "FD");
 
          } else if (shapeId === "triangle") {
            doc.triangle(
              ex + ew / 2, ey,
              ex + ew,     ey + eh,
              ex,          ey + eh,
              "FD"
            );
 
          } else if (shapeId === "rightTriangle") {
            doc.triangle(
              ex,      ey,
              ex + ew, ey + eh,
              ex,      ey + eh,
              "FD"
            );
 
          } else if (shapeId === "diamond") {
            // jsPDF has no polygon helper — draw as lines
            doc.setFillColor(
              Math.min(255, r + 40),
              Math.min(255, g + 40),
              Math.min(255, b + 80)
            );
            const pts = [
              [ex + ew / 2, ey],
              [ex + ew,     ey + eh / 2],
              [ex + ew / 2, ey + eh],
              [ex,          ey + eh / 2],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "arrowRight") {
            const head = ew * 0.35, shaft = eh * 0.35;
            const pts = [
              [ex,             ey + (eh - shaft) / 2],
              [ex + ew - head, ey + (eh - shaft) / 2],
              [ex + ew - head, ey],
              [ex + ew,        ey + eh / 2],
              [ex + ew - head, ey + eh],
              [ex + ew - head, ey + (eh + shaft) / 2],
              [ex,             ey + (eh + shaft) / 2],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "arrowLeft") {
            const head = ew * 0.35, shaft = eh * 0.35;
            const pts = [
              [ex + ew,        ey + (eh - shaft) / 2],
              [ex + head,      ey + (eh - shaft) / 2],
              [ex + head,      ey],
              [ex,             ey + eh / 2],
              [ex + head,      ey + eh],
              [ex + head,      ey + (eh + shaft) / 2],
              [ex + ew,        ey + (eh + shaft) / 2],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "star") {
            const outer = Math.min(ew, eh) / 2;
            const inner = outer * 0.4;
            const cx2 = ex + ew / 2, cy2 = ey + eh / 2;
            const pts = Array.from({ length: 10 }, (_, i) => {
              const ang = -Math.PI / 2 + i * Math.PI / 5;
              const rad = i % 2 === 0 ? outer : inner;
              return [cx2 + rad * Math.cos(ang), cy2 + rad * Math.sin(ang)];
            });
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "hexagon") {
            const cx2 = ex + ew / 2, cy2 = ey + eh / 2;
            const pts = Array.from({ length: 6 }, (_, i) => {
              const ang = i * Math.PI / 3;
              return [cx2 + (ew / 2) * Math.cos(ang), cy2 + (eh / 2) * Math.sin(ang)];
            });
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "pentagon") {
            const cx2 = ex + ew / 2, cy2 = ey + eh / 2;
            const pts = Array.from({ length: 5 }, (_, i) => {
              const ang = -Math.PI / 2 + i * (2 * Math.PI / 5);
              return [cx2 + (ew / 2) * Math.cos(ang), cy2 + (eh / 2) * Math.sin(ang)];
            });
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "callout") {
            const tail = eh * 0.25;
            if (ew > 0 && (eh - tail) > 0) {
              doc.roundedRect(ex, ey, ew, eh - tail, 2, 2, "FD");
              const pts = [
                [ex + ew * 0.2, ey + eh - tail],
                [ex + ew * 0.1, ey + eh],
                [ex + ew * 0.35, ey + eh - tail],
              ];
              drawPolygonPdf(doc, pts, cfg.accent);
            }
 
          } else if (shapeId === "parallelogram") {
            const skew = ew * 0.18;
            const pts = [
              [ex + skew, ey],
              [ex + ew,   ey],
              [ex + ew - skew, ey + eh],
              [ex,        ey + eh],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "trapezoid") {
            const inset = ew * 0.15;
            const pts = [
              [ex + inset, ey],
              [ex + ew - inset, ey],
              [ex + ew, ey + eh],
              [ex,      ey + eh],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else if (shapeId === "cross") {
            const t = Math.min(ew, eh) * 0.3;
            const pts = [
              [ex + (ew - t) / 2, ey],
              [ex + (ew + t) / 2, ey],
              [ex + (ew + t) / 2, ey + (eh - t) / 2],
              [ex + ew,           ey + (eh - t) / 2],
              [ex + ew,           ey + (eh + t) / 2],
              [ex + (ew + t) / 2, ey + (eh + t) / 2],
              [ex + (ew + t) / 2, ey + eh],
              [ex + (ew - t) / 2, ey + eh],
              [ex + (ew - t) / 2, ey + (eh + t) / 2],
              [ex,                ey + (eh + t) / 2],
              [ex,                ey + (eh - t) / 2],
              [ex + (ew - t) / 2, ey + (eh - t) / 2],
            ];
            drawPolygonPdf(doc, pts, cfg.accent);
 
          } else {
            // fallback: rectangle
            doc.rect(ex, ey, ew, eh, "FD");
          }
        }
 
        // ── TABLE ──────────────────────────────────────────────────────────
        if (el.type === "table" && el.data?.length > 0) {
          try {
            const rowCount = el.data.length;
            const colCount = el.data[0].length;
            const cellW = ew / colCount;
            const cellH = eh / rowCount;
 
            el.data.forEach((row, ri) => {
              row.forEach((cell, ci) => {
                const cellX = ex + ci * cellW;
                const cellY2 = ey + ri * cellH;
 
                if (ri === 0) {
                  doc.setFillColor(...cfg.accent);
                } else if (ri % 2 === 0) {
                  doc.setFillColor(17, 17, 48);
                } else {
                  doc.setFillColor(10, 10, 32);
                }
                doc.rect(cellX, cellY2, cellW, cellH, "F");
                doc.setDrawColor(51, 51, 102); doc.setLineWidth(0.3);
                doc.rect(cellX, cellY2, cellW, cellH, "S");
 
                if (ri === 0) {
                  doc.setTextColor(255, 255, 255);
                  doc.setFont("helvetica", "bold");
                  doc.setFontSize(Math.max(5, Math.min(7, cellH * 0.45)));
                } else {
                  doc.setTextColor(200, 200, 220);
                  doc.setFont("helvetica", "normal");
                  doc.setFontSize(Math.max(4.5, Math.min(6.5, cellH * 0.4)));
                }
                const cellText = String(cell).slice(0, 18);
                doc.text(cellText, cellX + cellW / 2, cellY2 + cellH / 2 + 1.5, { align: "center" });
              });
            });
          } catch (tblErr) {
            console.warn(`PDF slide ${si + 1}: table skipped —`, tblErr.message);
          }
        }
      });
 
      // Footer bar inside card
      doc.setFillColor(5, 5, 18);
      doc.rect(CARD_X, CARD_Y + CARD_H - 6, CARD_W, 6, "F");
      doc.setTextColor(70, 70, 110); doc.setFontSize(5.5); doc.setFont("helvetica", "bold");
      doc.text("NoteAI", CARD_X + 4, CARD_Y + CARD_H - 2);
 
      // Progress dots
      const dotTotal  = slides.length;
      const dotStartX = CARD_X + CARD_W - dotTotal * 5 - 4;
      slides.forEach((_, di) => {
        doc.setFillColor(
          di === si ? cfg.accent[0] : 60,
          di === si ? cfg.accent[1] : 60,
          di === si ? cfg.accent[2] : 80
        );
        doc.rect(dotStartX + di * 5, CARD_Y + CARD_H - 4, di === si ? 4 : 2.5, 1.5, "F");
      });
 
      addFooter(si + 2, totalPages);
    });
 
    resolve(doc.output("blob"));
  } catch (err) {
    reject(err);
  }
}

// ── Helper: draw a filled + stroked polygon in jsPDF ──────────────────────────
// jsPDF doesn't have a polygon method, so we use lines + fill
// ── Helper: draw a filled + stroked polygon in jsPDF ──────────────────────────
export function drawPolygonPdf(doc, pts, accentRgb) {
  if (!pts || pts.length < 2) return;
  try {
    if (doc.lines) {
      const moves = pts.slice(1).map((p, i) => [p[0] - pts[i][0], p[1] - pts[i][1]]);
      doc.lines(moves, pts[0][0], pts[0][1], [1, 1], "FD", true);
    } else {
      const minX = Math.min(...pts.map(p => p[0]));
      const minY = Math.min(...pts.map(p => p[1]));
      const maxX = Math.max(...pts.map(p => p[0]));
      const maxY = Math.max(...pts.map(p => p[1]));
      doc.rect(minX, minY, maxX - minX, maxY - minY, "FD");
    }
  } catch {
    // silent fallback
  }
}
